name:                variation
version:             0.3.0.0
github:              "cspollard/variation"
license:             BSD3
author:              "Chris Pollard"
maintainer:          "cspollard@gmail.com"
copyright:           "2019 Chris Pollard"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/test#readme>

dependencies:
- base
- cereal
- these
- deepseq
- containers
- semigroupoids
- linear
- semialign

library:
  source-dirs: src
